-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users Table
-- "Identity Initialization" - Anonymous, cookie-based identity.
CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY, -- Matches the cookie UUID
    identity_hash text NOT NULL, -- "SEC-ALPHA-9920-X"
    is_demo boolean DEFAULT false,
    uptime_seconds int DEFAULT 0,
    security_protocol text DEFAULT 'AES-256',
    specificity_level int DEFAULT 4,
    created_at timestamptz DEFAULT now()
);

-- 2. Sessions Table
-- "The Contract" - Tracks focus sessions.
CREATE TABLE IF NOT EXISTS sessions (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id uuid REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    status text NOT NULL, -- 'HOLD', 'RUNNING', 'LOCKED', 'COMPLETED', 'WARNING', 'ABANDONED'
    start_time bigint, -- Unix timestamp
    started_at_iso timestamptz, -- ISO string
    main_title text,
    progress_percent int DEFAULT 0,
    warning_triggered boolean DEFAULT false,
    duration_minutes int,
    created_at timestamptz DEFAULT now()
);

-- Enforce "One Active Session" Rule (from hardening.sql)
CREATE UNIQUE INDEX IF NOT EXISTS one_running_session
ON sessions(user_id)
WHERE status = 'RUNNING';

-- 3. Violations Table
-- "Failure & Penalty" - Tracks integrity violations.
CREATE TABLE IF NOT EXISTS violations (
    id text PRIMARY KEY, -- Generated by frontend/logic
    session_id uuid REFERENCES sessions(id) ON DELETE CASCADE NOT NULL,
    type text NOT NULL, -- 'PHONE_DETECTED', 'TAB_SWITCH', 'ABANDONED'
    timestamp_iso timestamptz NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 4. Tracks Table
-- "Syllabus" - The modules available for selection.
CREATE TABLE IF NOT EXISTS tracks (
    id text PRIMARY KEY, -- "SYL_MOD_06_UPLINK"
    name text NOT NULL,
    risk_level text NOT NULL, -- 'LOW', 'MEDIUM', 'HIGH'
    status text DEFAULT 'ACTIVE',
    created_at timestamptz DEFAULT now()
);

-- 5. Track Objectives (Templates)
-- Objectives belonging to a Track Module.
CREATE TABLE IF NOT EXISTS track_objectives (
    id text PRIMARY KEY, -- "OBJ_601_CORE"
    track_id text REFERENCES tracks(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    time_block text, -- "08:00 - 09:30"
    intensity text NOT NULL, -- 'LOW', 'MEDIUM', 'HIGH', 'URGENT'
    default_status text DEFAULT 'PENDING'
);

-- 6. Range Objectives (Session Instances)
-- Specific objectives queued for a session (The "Queue").
CREATE TABLE IF NOT EXISTS range_objectives (
    id text PRIMARY KEY, -- Instance ID or cloned ID
    session_id uuid REFERENCES sessions(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    time_block text,
    intensity text,
    status text,
    progress int DEFAULT 0
);

-- 7. Transactional Update Function (RPC)
-- Updates session state AND inserts violations atomically.
CREATE OR REPLACE FUNCTION update_session_with_violations(
  p_session_id uuid,
  p_status text,
  p_progress int,
  p_warning boolean,
  p_violations jsonb,
  p_main_title text
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  -- Update the Session
  UPDATE sessions
  SET
    status = p_status,
    progress_percent = p_progress,
    warning_triggered = p_warning,
    main_title = p_main_title
  WHERE id = p_session_id;

  -- Insert Violations (Ignore duplicates)
  -- Assumes violations list contains {id, type, timestamp}
  INSERT INTO violations (id, session_id, type, timestamp_iso)
  SELECT
    (v->>'id'),
    p_session_id,
    (v->>'type'),
    (v->>'timestamp')::timestamptz
  FROM jsonb_array_elements(p_violations) v
  ON CONFLICT (id) DO NOTHING;
END;
$$;
